# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 496)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_part = QtWidgets.QLabel(self.centralwidget)
        self.label_part.setObjectName("label_part")
        self.horizontalLayout_4.addWidget(self.label_part)
        self.label_full = QtWidgets.QLabel(self.centralwidget)
        self.label_full.setObjectName("label_full")
        self.horizontalLayout_4.addWidget(self.label_full)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)

        self.btnLoad_Full = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad_Full.setObjectName("btnLoad_Full")
        self.verticalLayout_3.addWidget(self.btnLoad_Full)

        self.btnLoad_Part = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad_Part.setObjectName("btnLoad_Part")
        self.verticalLayout_3.addWidget(self.btnLoad_Part)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.cbtnMAP = QtWidgets.QCheckBox(self.centralwidget)
        self.cbtnMAP.setObjectName("cbtnMAP")
        self.verticalLayout_2.addWidget(self.cbtnMAP)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btnMain = QtWidgets.QPushButton(self.centralwidget)
        self.btnMain.setEnabled(False)
        self.btnMain.setCheckable(False)
        self.btnMain.setChecked(False)
        self.btnMain.setAutoRepeatInterval(100)
        self.btnMain.setAutoDefault(False)
        self.btnMain.setObjectName("btnMain")
        self.verticalLayout.addWidget(self.btnMain)
        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 566, 21))
        self.menuBar.setObjectName("menuBar")

        self.menu_color = QtWidgets.QMenu(self.menuBar)
        self.menu_color.setObjectName("menu_color")

        self.menu_method = QtWidgets.QMenu(self.menuBar)
        self.menu_method.setObjectName("menu_method")
        MainWindow.setMenuBar(self.menuBar)

        self.btn_SQDIFF_NORMED = QtWidgets.QAction(MainWindow)
        self.btn_SQDIFF_NORMED.setCheckable(True)
        self.btn_SQDIFF_NORMED.setObjectName("btn_SQDIFF_NORMED")
        self.btn_CCOEFF = QtWidgets.QAction(MainWindow)
        self.btn_CCOEFF.setCheckable(True)
        self.btn_CCOEFF.setObjectName("btn_CCOEFF")
        self.btn_CCOEFF_NORMED = QtWidgets.QAction(MainWindow)
        self.btn_CCOEFF_NORMED.setCheckable(True)
        self.btn_CCOEFF_NORMED.setObjectName("btn_CCOEFF_NORMED")
        self.btn_CCORR = QtWidgets.QAction(MainWindow)
        self.btn_CCORR.setCheckable(True)
        self.btn_CCORR.setObjectName("btn_CCORR")
        self.btn_CCORR_NORMED = QtWidgets.QAction(MainWindow)
        self.btn_CCORR_NORMED.setCheckable(True)
        self.btn_CCORR_NORMED.setObjectName("btn_CCORR_NORMED")
        self.btn_SQDIFF = QtWidgets.QAction(MainWindow)
        self.btn_SQDIFF.setCheckable(True)
        self.btn_SQDIFF.setObjectName("btn_SQDIFF")

        self.btn_white = QtWidgets.QAction(MainWindow)
        self.btn_white.setCheckable(True)
        self.btn_white.setObjectName("btn_white")
        self.btn_black = QtWidgets.QAction(MainWindow)
        self.btn_black.setCheckable(True)
        self.btn_black.setObjectName("btn_black")
        self.btn_red = QtWidgets.QAction(MainWindow)
        self.btn_red.setCheckable(True)
        self.btn_red.setObjectName("btn_red")
        self.btn_orange = QtWidgets.QAction(MainWindow)
        self.btn_orange.setCheckable(True)
        self.btn_orange.setObjectName("btn_orange")
        self.btn_yellow = QtWidgets.QAction(MainWindow)
        self.btn_yellow.setCheckable(True)
        self.btn_yellow.setObjectName("btn_yellow")
        self.btn_green = QtWidgets.QAction(MainWindow)
        self.btn_green.setCheckable(True)
        self.btn_green.setObjectName("btn_green")
        self.btn_blue = QtWidgets.QAction(MainWindow)
        self.btn_blue.setCheckable(True)
        self.btn_blue.setObjectName("btn_blue")
        self.btn_purple = QtWidgets.QAction(MainWindow)
        self.btn_purple.setCheckable(True)
        self.btn_purple.setObjectName("btn_purple")

        self.menu_color.addAction(self.btn_white)
        self.menu_color.addAction(self.btn_black)
        self.menu_color.addAction(self.btn_red)
        self.menu_color.addAction(self.btn_orange)
        self.menu_color.addAction(self.btn_yellow)
        self.menu_color.addAction(self.btn_green)
        self.menu_color.addAction(self.btn_blue)
        self.menu_color.addAction(self.btn_purple)

        self.menu_method.addAction(self.btn_SQDIFF)
        self.menu_method.addAction(self.btn_SQDIFF_NORMED)
        self.menu_method.addAction(self.btn_CCOEFF)
        self.menu_method.addAction(self.btn_CCOEFF_NORMED)
        self.menu_method.addAction(self.btn_CCORR)
        self.menu_method.addAction(self.btn_CCORR_NORMED)

        self.menuBar.addAction(self.menu_color.menuAction())
        self.menuBar.addAction(self.menu_method.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_part.setText(_translate("MainWindow", "Здесь будет искомое изображение"))
        self.label_full.setText(_translate("MainWindow", "Здесь будет полное изображение"))

        self.btnLoad_Full.setText(_translate("MainWindow", "Загрузка полного изображения"))
        self.btnLoad_Part.setText(_translate("MainWindow", "Загрузка искомого изображения"))

        self.cbtnMAP.setText(_translate("MainWindow", "Сохранять полученную тепловую карту"))

        self.btnMain.setText(_translate("MainWindow", "Найти фрагмент на изображении"))

        self.menu_color.setTitle(_translate("MainWindow", "Цвет"))
        self.menu_method.setTitle(_translate("MainWindow", "Метод"))

        self.btn_SQDIFF_NORMED.setText(_translate("MainWindow", "Нормированный квадрат разности"))
        self.btn_CCOEFF.setText(_translate("MainWindow", "Коэффициент ковариации"))
        self.btn_CCOEFF_NORMED.setText(_translate("MainWindow", "Коэффициент корреляции Пирсона"))
        self.btn_CCORR.setText(_translate("MainWindow", "Коэффициент кросс-корреляции"))
        self.btn_CCORR_NORMED.setText(_translate("MainWindow", "Нормированный коэффициент кросс-корреляции"))
        self.btn_SQDIFF.setText(_translate("MainWindow", "Квадрат разности"))

        self.btn_white.setText(_translate("MainWindow", "Белый"))
        self.btn_black.setText(_translate("MainWindow", "Чёрный"))
        self.btn_red.setText(_translate("MainWindow", "Красный"))
        self.btn_orange.setText(_translate("MainWindow", "Оранжевый"))
        self.btn_yellow.setText(_translate("MainWindow", "Жёлтый"))
        self.btn_green.setText(_translate("MainWindow", "Зелёный"))
        self.btn_blue.setText(_translate("MainWindow", "Синий"))
        self.btn_purple.setText(_translate("MainWindow", "Фиолетовый"))
